### PR TITLE
Adds a counter property to Collection and removes route

### PR DESCRIPTION
**Pull request by nbilenko**
---
name: Counter property added to Collection, route removed
about: https://github.com/openoakland/woeip/issues/136
labels: MVP, backend, database
reviewers: ifed3, r-b-g-b, theecrit
---

## Checklist
- [x] Add description
- [x] Reference open issue pull request addresses
- [x] Pass linting check
  - complete on the local machine with `make local.shell` `make quality`
- [x] Pass functional tests
  - complete on the local machine with `make local.shell` `make test`
- [x] Request code review
  - Please allow **36 hours** from opening a pull request before merging a pull request- even if it has already recieved an approving review.
- [ ] Address comments on code and resolve requested changes
- [ ] Merge own code

## Description
Issue: https://github.com/openoakland/woeip/issues/136

* Adds a counter property to the Collection object, which returns the counter of the collection on that date (e.g. if `my_collection` is the earliest collection on September 17th, `my_collection.counter` would be `0`). Also adds a string representation for the Collection object that prints the collection date and the counter in a 1-indexed format (e.g. `print(my_collection)` would output `'Collection 1 on Sep 17 2019'`).

* Removes route field from Collection (not used).

### CODE REVIEW

**Comment by theecrit** [comment]
@nbilenko I'll defer to @ifed3 and/or @r-b-g-b for code review, but my only bit of feedback is on:

> Also adds a string representation for the Collection object that prints the collection date and the counter in a 1-indexed format (e.g. print(my_collection) would output 'Collection 1 on Sep 17 2019').

I'm wondering if this syntax eliminates flexibility on the front-end? In other words: what if we decide, when designing the View Map interface, that we want the page title to reflect the session date, but the sequence number to appear elsewhere (as in [the last page of this wireframe](https://drive.google.com/open?id=1kP2MIls9wsYGffVQS1F-9gQolBWv_YO2)).

Just want to make sure this output syntax doesn't handcuff us on the front-end design. Other than that, looking good to me!

**Comment by nbilenko** [comment]
> @nbilenko I'll defer to @ifed3 and/or @r-b-g-b for code review, but my only bit of feedback is on:
> 
> > Also adds a string representation for the Collection object that prints the collection date and the counter in a 1-indexed format (e.g. print(my_collection) would output 'Collection 1 on Sep 17 2019').
> 
> I'm wondering if this syntax eliminates flexibility on the front-end? In other words: what if we decide, when designing the View Map interface, that we want the page title to reflect the session date, but the sequence number to appear elsewhere (as in [the last page of this wireframe](https://drive.google.com/open?id=1kP2MIls9wsYGffVQS1F-9gQolBWv_YO2)).
> 
> Just want to make sure this output syntax doesn't handcuff us on the front-end design. Other than that, looking good to me!

This printout is just for internal convenience - while it *could* in principle be used, the `counter` is what should be used programmatically on the front-end, and it's just a number.

**Comment by theecrit** [comment]
Ok, that's what I wasn't sure of, thanks!

**Comment by ifed3** [comment]
@nbilenko this is less of a counter and more of a sorted position index which is an intensive operation. To get information about 1 collection, you have to interact with every other collection. So if there are 100 collections, to find the position of each one you would have to repeat sorting the list of collections 100 times. As the number of collections in the db grows, this property computation will get slower. Additionally insert or delete operations can cause race conditions while the sorting is happening which will give positional skips or holes.

@theecrit For this reason and others below, I would suggest dropping "counters" entirely. Counters in this case act as a lossy proxy for sorting by time of day (ToD). This type of sorting is more ideal for client usage.

It would be simpler for the client to receive pertinent collections, sort by start timestamp and figure the position of the current collection in the array of sorted collections. This also allows the user to toggle UI parameters to figure out which sequence view they desire.

In terms of display, information is lost by using a position index instead of the actual ToD. Looking at [the last page of the map view wireframe](https://drive.google.com/open?id=1kP2MIls9wsYGffVQS1F-9gQolBWv_YO2), we can simply replace `Session 1` and `Session 2` with the actual time durations: `10:30am - 11:30 am` and `1:30 pm - 2:30pm`. That conveys more direct information at a quick glance than a numerical order since the user doesn't have to click into `Session 1` to figure out when the collection took place.

**Comment by nbilenko** [comment]
> @nbilenko this is less of a counter and more of a sorted position index which is an intensive operation. To get information about 1 collection, you have to interact with every other collection. So if there are 100 collections, to find the position of each one you would have to repeat sorting the list of collections 100 times. As the number of collections in the db grows, this property computation will get slower. Additionally insert or delete operations can cause race conditions while the sorting is happening which will give positional skips or holes.

The property gets evaluated when called, and django uses lazy querying for querysets, so the SQL wouldn't run until the return. There also shouldn't be a race condition since the property is not saving anything to the db - it's only in python.

Re: sorting, I definitely agree that's a good thing to think through carefully. My thinking behind this was that since the sorting happens after filtering by date, it would only sort the number of sessions on that date, and that's unlikely to be prohibitively large. Also, we likely wouldn't be displaying the counter for large numbers of sessions at a time, and that limits the number of calls we would make to this property. Do you foresee a situation where this would be very big?

**Comment by theecrit** [comment]
@ifed3 
> It would be simpler for the client to receive pertinent collections, sort by start timestamp and figure the position of the current collection in the array of sorted collections. This also allows the user to toggle UI parameters to figure out which sequence view they desire.

Yeah, I hear what you're saying. In some use cases, *sort order* is appropriate (e.g. displaying session thumbnails in order in a gallery view). But there's another use case, which is as an identifier (e.g. displaying the sequence # in the UI, as in "Sept. 28, session 2"). Would your proposed alternative allow for this additional use case?

**Comment by nbilenko** [comment]
> > @nbilenko this is less of a counter and more of a sorted position index which is an intensive operation. To get information about 1 collection, you have to interact with every other collection. So if there are 100 collections, to find the position of each one you would have to repeat sorting the list of collections 100 times. As the number of collections in the db grows, this property computation will get slower. Additionally insert or delete operations can cause race conditions while the sorting is happening which will give positional skips or holes.
> 
> The property gets evaluated when called, and django uses lazy querying for querysets, so the SQL wouldn't run until the return. There also shouldn't be a race condition since the property is not saving anything to the db - it's only in python.
> 
> Re: sorting, I definitely agree that's a good thing to think through carefully. My thinking behind this was that since the sorting happens after filtering by date, it would only sort the number of sessions on that date, and that's unlikely to be prohibitively large. Also, we likely wouldn't be displaying the counter for large numbers of sessions at a time, and that limits the number of calls we would make to this property. Do you foresee a situation where this would be very big?

I actually just realized the sorting operation was unnecessary.

**Comment by ifed3** [comment]
@theecrit Alright if we want to have the sequence, it's clear that only the frontend would ever use the sequence. Internal calls would simply filter by day and sort by timestamp.

With that, @nbilenko I would suggest moving the sequence computing from the model and only making it available to the frontend via an api request to `/collections/:id/sequence`

This is far more flexible since there can be multiple collection sequences to check. Here are just a few:

1. The order of this session in all sessions collected by anyone
2. The order of this session in all sessions collected by me
3. The order of this session in all sessions uploaded by me
4. The order of this session in all sessions collected and uploaded by me

If we let the sequence determination happen on the model, we can only account for # 1. However if we do it as an api request, then we can send additional data along to have a more specific request sequence determination

An example is as follows:

Request:

GET /collections/5/sequence

```js
params = {
  duration: 'today'
  collection: 'all', // one of ['all', 'collected', 'uploaded', 'collected_and_uploaded']
}
```

Response: 
```js
{
  order: 3, // 1-based index to allow for Session 3
  sequence: [10, 2, 5, 8, 1] // List of Collection ids in sequence for simple routing, i.e view Session 1 links to /collections/10
}
```

**Comment by nbilenko** [comment]
> With that, @nbilenko I would suggest moving the sequence computing from the model and only making it available to the frontend via an api request to `/collections/:id/sequence`
> 
> This is far more flexible since there can be multiple collection sequences to check. Here are just a few:
> 
> 1. The order of this session in all sessions collected by anyone
> 2. The order of this session in all sessions collected by me
> 3. The order of this session in all sessions uploaded by me
> 4. The order of this session in all sessions collected and uploaded by me
> 
> If we let the sequence determination happen on the model, we can only account for # 1. However if we do it as an api request, then we can send additional data along to have a more specific request sequence determination
> 
> An example is as follows:
> 
> Request:
> 
> GET /collections/5/sequence
> 
> ```js
> params = {
>   duration: 'today'
>   collection: 'all', // one of ['all', 'collected', 'uploaded', 'collected_and_uploaded']
> }
> ```
> 
> Response:
> 
> ```js
> {
>   order: 3, // 1-based index to allow for Session 3
>   sequence: [10, 2, 5, 8, 1] // List of Collection ids in sequence for simple routing, i.e view Session 1 links to /collections/10
> }
> ```

Sure, the property can be made available via API request (I can make a new PR for that). Keeping it as a property would be better than calculating it within the request itself though, since then it will be available to all requests (and it seems like that may be needed). The cases you're describing can be covered by either adding arguments to the property or adding new properties - I didn't handle them in this PR since they aren't MVP.

**Comment by nbilenko** [comment]
@ifed3 If I'm interpreting correctly, your general point is that this functionality could be implemented in the frontend altogether, which is true. The implementation I'm proposing uses a model property for two reasons: it might be used in multiple contexts by the frontend so it would be good to prevent that redundancy, and is a cheap attribute to compute on the backend. So overall, it would allow for more flexibility.

**Comment by theecrit** [comment]
> @ifed3 If I'm interpreting correctly, your general point is that this functionality could be implemented in the frontend altogether, which is true. The implementation I'm proposing uses a model property for two reasons: it might be used in multiple contexts by the frontend so it would be good to prevent that redundancy, and is a cheap attribute to compute on the backend. So overall, it would allow for more flexibility.

I'm inclined to keep it as a property unless there's a strong reason _not_ to.


>  it's clear that only the frontend would ever use the sequence. 

Does this assumption need vetting?

**Comment by ifed3** [comment]
@nbilenko Not necessarily. I'm fine with it being computed on the backend. My concern is specifically that the computation is happening in a property attribute.

Properties are simple and usually based only on direct manipulation of self attributes of the model. Right now this property requires non-self attributes resulting from an expensive database call to get all collections to filter from.

This means once a collection object is serialized it's gonna include the counter property whether or not the caller needs it, thus making unnecessary database calls.

A solution for avoiding redundancy is to make the counter an instance method. Then the way for the external world to interface that method would be through an api call of `/collections/:id/sequence`.

So if a frontend component only needs the collection info, it calls `/collections/:id`, if it only needs the collection sequence, it calls `/collections/:id/sequence`, and if it needs both, it calls both.

What I'm trying to avoid is always sending the sequence irrespective of whether a component needs it since then we're hitting the database for no reason.

**Comment by nbilenko** [comment]
> @nbilenko Not necessarily. I'm fine with it being computed on the backend. My concern is specifically that the computation is happening in a property attribute.
> 
> Properties are simple and usually based only on direct manipulation of self attributes of the model. Right now this property requires non-self attributes resulting from an expensive database call to get all collections to filter from.
> 
> This means once a collection object is serialized it's gonna include the counter property whether or not the caller needs it, thus making unnecessary database calls.
> 
> A solution for avoiding redundancy is to make the counter an instance method. Then the way for the external world to interface that method would be through an api call of `/collections/:id/sequence`.
> 
> So if a frontend component only needs the collection info, it calls `/collections/:id`, if it only needs the collection sequence, it calls `/collections/:id/sequence`, and if it needs both, it calls both.
> 
> What I'm trying to avoid is always sending the sequence irrespective of whether a component needs it since then we're hitting the database for no reason.

I think it's a pretty cheap call (as discussed above), but I agree we might as well avoid the possibility of it becoming a concern. I converted the property to an instance method. I'll add the request in a new PR.

**Review by ifed3 — APPROVED** [review]
thanks for taking my concerns into consideration, appreciate it!

**Comment by nbilenko** [comment]
> thanks for taking my concerns into consideration, appreciate it!

Thank you for raising them!!

**Pull request merged**
