### PR TITLE
Clean up static assets changes

### PR DESCRIPTION
**Pull request by ifed3**
---
name: Code change clean up
about: Fix some minor elements with previous PR
title: Clean up static assets changes
labels: ''
reviewers: @jayqi

---

## Checklist
- [X] Add description
- [ ] Reference open issue pull request addresses
- [X] Pass functional tests
  - complete on the local machine with `make local.shell` `make test`
- [X] Request code review
  - Please allow **36 hours** from opening a pull request before merging a pull request- even if it has already recieved an approving review.
- [ ] Address comments on code and resolve requested changes
- [ ] Merge own code

## Description
Issue: Base docker file was edited instead of specific env file, generic file name used for nginx routing config

- Moved docker-compose volume config from docker-compose.yml to dev docker file (docker-compose.overrides.yml)
- Renamed nginx-proxy/api_location to nginx-proxy/api_static_assets_routing
- Provided comment on api/entrypoint.sh for collectstatic make command usage

### CODE REVIEW

**Comment by jayqi** [comment]
@ifed3 What is different about how the app is deployed in production that makes this unnecessary? This was something @r-b-g-b and I were talking about yesterday but didn't really understand.

**Comment by ifed3** [comment]
@jayqi great question! Currently the prod env is still in flux. There's no guarantee it will end up as a fully unified docker env in the same way dev is.

Currently the [frontend](beta.woaq.org) is hosted on Zeit. The [backend](api.woaq.org) is hosted via Heroku's container registry. At the moment, Nginx isn't involved in prod. I would like to change that in the future but haven't done any work with that since we aren't particularly close to the app being ready for prod deployment.

So for the time being, update only the dev env and once things are ready for prod, the focus can be on deciding what's easiest to deploy and maintain for the prod env.

**Comment by theecrit** [comment]
@ifed3 Side note: does this part of the ReadMe (under "Quickstart for Developers") need updating to beta.woaq.org? 

> Browse the client at lvh.me, ping the api at api.lvh.me.

(cc @lukehtravis — this is what I was looking for earlier; I'd forgotten about beta.woaq.org. 🤦🏻‍♀️)

**Comment by ifed3** [comment]
@theecrit not yet. Most of the instructions are focused primarily on local dev. 

Everything about staging and prod is still in flux. So for example the beta.woaq.org is something I have to manually deploy. I haven't yet created an automatic way for that to happen.

Once we get to a good point where we're beyond developing and ready to start deploying to prod, then there's a lot of discussions we need to have

**Comment by theecrit** [comment]
@ifed3 Makes sense, thanks for clarifying.

**Review by jayqi — APPROVED** [review]
LGTM. Thanks for clarifying about the prod vs. dev environment.

**Pull request merged**
