### PR TITLE
Ty about

### PR DESCRIPTION
**Pull request by TangoYankee**
The same as js-about. But, it reactifies the class names, creates a sticky footer, and removes the font size adjustment that was creating problems in the production build.

Addresses #377 and #246

### CODE REVIEW

**Comment by theecrit** [comment]
@TangoYankee Does this fix the sticky footer across the site? We have a separate issue open for that, and I think it makes more sense to open a separate PR that fixes it globally, rather than requiring every new page to address it independently, no? Maybe I'm misunderstanding the fix you included, though.

**Comment by theecrit** [comment]
Also, what does `reactifies the class names` mean? :)

**Comment by TangoYankee** [comment]
> 
> 
> Also, what does `reactifies the class names` mean? :)

React uses `className` instead of `class`. We had `class` in a few places. I just made a quick update.

**Comment by TangoYankee** [comment]
> 
> 
> TangoYankee Does this fix the sticky footer across the site? We have a separate issue open for that, and I think it makes more sense to open a separate PR that fixes it globally, rather than requiring every new page to address it independently, no? Maybe I'm misunderstanding the fix you included, though.

It's a global fix that would close the footer issue. (It's technically poor form to combine multiple Issues into a single PR. But, the footer looked so bad on the About page and it was so easy to fix globally that I threw it in as  a bonus.)

**Comment by theecrit** [comment]
Okay sweet, that all makes sense. I've updated all the issues you didn't 😉. I suppose this means we can kill my PR? I'm just troubleshooting a build fail on oo.org and will try to review and merge this in the next day or so. I'd like to review it for practice. :)

**Comment by TangoYankee** [comment]
> 
> 
> Okay sweet, that all makes sense. I've updated all the issues you didn't 😉. I suppose this means we can kill my PR? I'm just troubleshooting a build fail on oo.org and will try to review and merge this in the next day or so. I'd like to review it for practice. :)

sounds good. Oh! and the font-size css that you noticed was the source of  #296. So these changes also remove that css. We can also close #296 with this PR.

**Pull request merged**
