### PR TITLE
adds unit tests for upload form

### PR DESCRIPTION
**Pull request by nbilenko**
Add some simple tests for the DustrakForm

### CODE REVIEW

**Review by TangoYankee — CHANGES_REQUESTED** [review]
@theecrit Is currently refining the requirements for forms. This may change what tests need to be performed. Once the requirements are refined, we can open an issue to confirm the test requirements. From there, we can review this PR against the issue requirements. 

It may seem tedious and get a little frustrating. However, I want to respect the time of everyone that contributes to this project. That means keeping the whole team on the same page to make sure we're writing the code (basically) correctly on the first try.

Edit: Issue #59

**Comment by theecrit** [comment]
I should be able to make some progress this weekend — thanks for your patience!

**Comment by nbilenko** [comment]
Certainly sounds reasonable! But this just tests that the current code works.

**Comment by TangoYankee** [comment]
Yeah... the current code may change.

**Comment by theecrit** [comment]
@nbilenko @TangoYankee Is this still blocked? I'm unclear what form-related specifics I need to provide to unblock it. Let me know; thanks!

**Comment by nbilenko** [comment]
AFAIK we are doing fine on requirements, but this is currently blocked by the fact that the forms will be adjusted after we change the database schema.
The tests can be incorporated in the next code change for the forms. As a general practice, it would be great if we accompany code changes with corresponding unit tests in pull requests.

This PR/branch will be abandoned but I'll wait to delete for now in case it might be useful for the next form iteration.

**Comment by nbilenko** [comment]
Closing due to move to REST framework.

**Pull request closed without merging**
