### PR TITLE
Refactor dustrak load and join functions

### PR DESCRIPTION
**Pull request by r-b-g-b**
A few changes to the dustrak loader and joiner. Most importantly, raise ``ValueError`` when air quality or gps files do not load. Return the error message that the loader raised. Also, open the files in binary mode and catch multiple different kinds of line endings when parsing the header.

### CODE REVIEW

**Review by TangoYankee — CHANGES_REQUESTED** [review]
Update the doc string to specify that the file is being read in binary mode and why it is done that way

**Review by clintonb — CHANGES_REQUESTED** [review]
Why are you opening a text file in binary mode?

**Comment by r-b-g-b** [comment]
This function is meant to process data files uploaded via the web form. The ``request.FILES['air_quality']`` file opens in binary mode, so this function is made to handle that.

**Comment by r-b-g-b** [comment]
See this for an example for how the function is used: https://github.com/openoakland/woeip/blob/r-b-g-b/upload-form/woeip/apps/air_quality/views.py

**Comment by clintonb** [comment]
I see now. Your files need to be decoded as UTF-8. In general, if you are working with text, work with text. Avoid introducing binary strings to keep encoding/decoding simple. In this case, you need to update https://github.com/openoakland/woeip/blob/r-b-g-b/upload-form/woeip/apps/air_quality/views.py#L40-L41 to decode the files before passing them in.

Try updating these lines to:

```python
from django.utils.encoding import smart_text
...
joined_data = dustrak.join(smart_text(request.FILES['air_quality'].read()),
                           smart_text(request.FILES['gps'].read()))
```

[`smart_text`](https://docs.djangoproject.com/en/2.1/ref/utils/#django.utils.encoding.smart_text) will decode the input files to a proper UTF-8 `str`.

**Comment by clintonb** [comment]
Correction: use `force_text` as recommended by https://docs.djangoproject.com/en/2.1/ref/unicode/#useful-utility-functions.

**Comment by r-b-g-b** [comment]
Whoooa

**Comment by r-b-g-b** [comment]
Ok in that case, this PR is pretty straightforward: catching errors if air quality and gps files are not formatted correctly.

**Comment by TangoYankee** [comment]
@r-b-g-b Before merging this PR, could you create an issue which outlines the conversion of `views` to include `force_text`, to avoid losing track of the task?

Also, delete *open files in binary mode* from PR name?

**Comment by r-b-g-b** [comment]
That is a part of the file upload issue, I'll make note of it there. :+1:

**Review by TangoYankee — APPROVED** [review]

**Comment by r-b-g-b** [comment]
@clintonb Does this look ready to merge now?

**Review by clintonb — CHANGES_REQUESTED** [review]
Ditch the file streams/handles, and stick with strings throughout. The quicker you can get to a UTF-8 string, the simpler the code will be.

**Comment by r-b-g-b** [comment]
Yeah, the annoying thing is that there doesn't appear to be a pandas method that loads directly from stream. So it's necessary to wrap any string in a ``io.StringIO`` at some point. I could move that inside the ``dustrak.joiner``, but I figured it was more natural for a loader to accept a file handle-like object than a string containing the file contents.

**Comment by clintonb** [comment]
It's not necessarily more natural to accept a file handle, especially given we aren't explicitly operating on files. If you use `string` at the interface, you can push the file-handling logic solely to the places where it's needed.

The term "loader" doesn't really mean anything, so we can do whatever we want.

**Comment by r-b-g-b** [comment]
Yeah, after thinking it over I came around to that same conclusion. It's not a "loader," it's a "joiner" which should operate on already loaded things. At least I feel better if I think about it that way :P

**Comment by r-b-g-b** [comment]
Ok a bit of a refactor. I made the loaders ``load_dustrak`` and ``load_gps`` take file contents. ``join`` then takes the already-loaded dataframes, which I think makes a bit more sense.

**Comment by r-b-g-b** [comment]
The funny thing is that now those load functions will be called from the view, and any errors can be raised there. So the title of this PR is now... "Make stuff, like, kinda different"

**Review by clintonb — APPROVED** [review]

**Review by TangoYankee — APPROVED** [review]

**Pull request merged**
