### PR TITLE
Update Readme.md to include more context

### PR DESCRIPTION
**Pull request by theecrit**
- Added table of contents w/ anchor links for easy navigation
- Moved About.md content back into Readme.md (after Quick Start)
- Removed About.md since it's now superfluous
- Added project documentation links back into Readme (after Quick Start)

---
name: Pull Request for Issue #127 
about: Request merging changes into the code base

---

## Checklist
- [x] Add description
- [x] Reference open issue pull request addresses
- [x] Pass linting check
  - complete on the local machine with `make local.shell` `make quality`
- [x] Pass functional tests
  - complete on the local machine with `make local.shell` `make test`
- [x] Request code review
  - Please allow **36 hours** from opening a pull request before merging a pull request- even if it has already recieved an approving review.
- [ ] Address comments on code and resolve requested changes
- [ ] Merge own code

### CODE REVIEW

**Comment by nbilenko** [comment]
@theecrit Changes look good, but several `.DS_Store` files got added. This is because with the latest update, we have different `.gitignore` files under different sections of the codebase but no top-level `.gitignore` file.
To fix this, could you remove all the `.DS_Store` files from this commit (using `git rm --cached <filepath>` for each file), and also create a file at the same level as the Readme called `.gitignore` that contains the text `.DS_Store`?

**Comment by theecrit** [comment]
@nbilenko Oh crap, didn't even catch that, thanks. Will do!

**Comment by theecrit** [comment]
@nbilenko @ifed3 Ready for your review, thanks!

**Review by nbilenko — APPROVED** [review]
LGTM!

**Comment by theecrit** [comment]
TY!

**Pull request merged**
